usr/lib/${DEB_HOST_MULTIARCH}/qt6/examples/datavisualization/graphgallery/graphgallery
usr/lib/${DEB_HOST_MULTIARCH}/qt6/examples/datavisualization/qmlaxishandling/qmlaxishandling
usr/lib/${DEB_HOST_MULTIARCH}/qt6/examples/datavisualization/qmlbars/qmlbars
usr/lib/${DEB_HOST_MULTIARCH}/qt6/examples/datavisualization/qmlscatter/qmlscatter
usr/lib/${DEB_HOST_MULTIARCH}/qt6/examples/datavisualization/qmlsurfacegallery/qmlsurfacegallery
usr/lib/${DEB_HOST_MULTIARCH}/qt6/examples/datavisualization/volumetric/volumetric
